config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  devise_for :candidates, path: 'candidates'
  devise_for :employees, path: 'employees', controllers: { registrations: "registrations" }
  resource :search, only: [:show]
  resource :candidate, only: [:show] 
  resources :job_candidates, only: [:index, :show, :edit, :update]
  resources :companies, only: [:index, :edit, :update, :show]
  resources :jobs, only:[:index, :show, :new, :create, :edit, :update] do
    post 'disable', on: :member
  end
  resources :proposals, only: [:new, :create, :edit, :update]  

  namespace 'api', defaults: { format: :json } do
    namespace 'v1' do
      resources :companies, only: [:show]
    end
  end

end

app/models/job.rb
class Job < ApplicationRecord
    belongs_to :company    
    has_many :jobcandidate
    before_validation :ensure_change_status

    enum salary: { undefined: 0, under: 1, between: 2, above: 3 }
    enum stage: { junior: 0, full: 1, senior: 2 }
    enum status: { active: true, inactive: false }

    validates :title, presence: true
    validates :need, presence: true
    validates :expiration, presence: true
    validates :quantity, presence: true
    validates :description, presence: true

    def self.search(search)        
        @result_search = Job.where('title LIKE ?', "%#{search}%")                
    end    

    def vaga_occupied
        qtd = self.quantity - 1
        self.update_attribute(:quantity, qtd)     
        if qtd == 0
            self.update_attribute(:status, false)        
        end          
    end

    private
        def ensure_change_status                     
            self.status = true
        end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController    
    before_action :authenticate_employee!, except: [:show, :index]
    
    def index
        if current_employee
            @jobs = Job.all
        else    
            @jobs = Job.where(status: true)
        end
    end

    def show
        @job = Job.find(params[:id])
        if current_employee
            if current_employee.company == @job.company
              @logado = true
            else
              @logado = false
            end
        else
            @logado = false
        end        
    end
    
    def new
        @job = Job.new
        @cadastro = true
    end

    def create      
        update_params = job_params
        update_params[:company] = current_employee.company
        @job = Job.new(update_params)
        if @job.save
            redirect_to @job
        else
            render :new
        end
    end

    def edit
        @job = Job.find(params[:id])
        @cadastro = true
      end
    
    def update
        @job = Job.find(params[:id])

        if @job.update(job_update_params)
            redirect_to @job
        else
            render :edit
        end
    end

    def disable
        @job = Job.find(params[:id])
        @job.update_attribute(:status, false)        
        redirect_to jobs_path
    end    

    private
        def job_params
            params.require(:job).permit(:title, :description, :salary, :stage, :need, :expiration, :quantity, :company)            
        end 

        def job_update_params
            params.require(:job).permit(:title, :description, :salary, :stage, :need, :expiration, :quantity)            
        end        
end

app/views/jobs/_form.html.erb
 <div class="container">
    <%=form_with(model: @job) do |f| %>                
    <div class="row">    
        <div class="col-3 font-weight-bold"><%= f.label :title, 'Titulo', class: "control-label"  %></div>
        <div class="col-9"><%= f.text_field :title, class: "form-control" %></div>
    </div>
    <br/>
    <div class="row">
        <div class="col-3 font-weight-bold"><%= f.label :description, 'Descrição', class: "control-label" %></div>
        <div class="col-9"><%= f.text_area :description, class: "form-control" %></div>
    </div>
    <br/>
    <div class="row">
        <div class="col-3 font-weight-bold"><%= f.label :salary, 'Faixa Salarial', class: "control-label" %></div>
        <div class="col-3"><%= f.select :salary, options_for_select(Job.salaries.map {|k, v| [I18n.t("activerecord.attributes.job.salary.#{k}"), k]}, f.object.salary), {}, class:'form-control' %></div>
        <div class="col-3 font-weight-bold"><%= f.label :stage, 'Nível', class: "control-label" %></div>
        <div class="col-3"><%= f.select :stage, options_for_select(Job.stages.map {|k, v| [I18n.t("activerecord.attributes.job.stage.#{k}"), k]}, f.object.stage), {}, class:'form-control' %></div>
    </div>        
    <br/>
    <div class="row">
        <div class="col-3 font-weight-bold"><%= f.label :need, 'Requisitos Obrigatórios', class: "control-label" %></div>
        <div class="col-9"><%= f.text_area :need, class: "form-control" %></div>            
    </div>
    <br/>
    <div class="row">
        <div class="col-3 font-weight-bold"><%= f.label :expiration, 'Data Limite', class: "control-label" %></div>
        <div class="col-3"><%= f.text_field :expiration, class: "form-control" %></div>
        <div class="col-3 font-weight-bold"><%= f.label :quantity, 'Total de Vagas', class: "control-label" %></div>
        <div class="col-3"><%= f.text_field :quantity, class: "form-control" %></div>                
    </div>
    <br/>
    <% @job.errors.full_messages.each do |message| %>
        <li class="alert alert-danger"><%= message %></li>
    <%end%>  
    <br/>
    <% if @cadastro %>
        <%= f.hidden_field :company, value: current_employee.company.id %>       
    <% end %>        
    <div class="text-center">
        <p><%= f.submit 'Salvar', :class => "btn btn-success" %></p>                    
    </div>
    <% end %>            
</div>

app/views/jobs/edit.html.erb
<!-- Bootstrap -->
<div class="well text-center">     
    <br/><h2>Edição da Vaga</h2><br/>
</div>
<%= render "form", article: @job %>

app/views/jobs/index.html.erb
<!-- Bootstrap -->
<div class="well text-center">    
  <br/><h2>Relação de Vagas</h2><br/>
</div>
<div class="container">
  <table class="table">
    <thead>
      <tr>
        <th scope="col">Empresa</th>
        <th scope="col">Vaga</th>
        <th scope="col">Status</th>
        <th scope="col">Link</th>
      </tr>
    </thead>
    <tbody>
      <% @jobs.each do |job| %>
        <% if job.active? && job.expiration >= DateTime.now%> 
          <tr>             
            <td><%= job.company.name %>        
            <td><%= job.title %></td>                  
            <td><%= I18n.t("activerecord.attributes.job.status.#{job.status}") %></td> 
            <td><%= link_to "Ver essa vaga", job, :class => "btn btn-primary" %></td>       
          </tr>
        <% end %>
      <% end %>  
    </tbody>
  </table>
  <% if employee_signed_in? %>    
    <p><%= link_to "Cadastrar Vaga", new_job_path, :class => "btn btn-success" %></p>
  <% end %>
</div>

app/views/jobs/new.html.erb
<!-- Bootstrap -->
<div class="well text-center">    
    <br/><h2>Cadastro da Vaga</h2><br/>
</div>
<%= render "form", article: @job %>

app/views/jobs/show.html.erb
<!-- Bootstrap -->
<div class="well text-center">    
    <br/><h2>Visualização da Vaga</h2><br/>
</div>    
    <div class="container">
        <div class="row">
            <div class="col-3 font-weight-bold">Titulo</div>
            <div class="col-9"><%=@job.title%></div>            
        </div> 
        <br/>       
        <div class="row">
            <div class="col-3 font-weight-bold">Nível</div>
            <div class="col-3"><%=I18n.t("activerecord.attributes.job.stage.#{@job.stage}")%></div>
            <div class="col-3 font-weight-bold">Faixa Salarial</div>
            <div class="col-3"><%=I18n.t("activerecord.attributes.job.salary.#{@job.salary}")%></div>            
        </div>
        <br/>   
        <div class="row">
            <div class="col-3 font-weight-bold">Requisitos Obrigatórios</div>
            <div class="col-9"><%=@job.need%></div>
        </div>
        <br/>   
        <div class="row">
            <div class="col font-weight-bold">Data Limite</div>
            <div class="col"><%= I18n.localize(@job.expiration, format: :long)%></div>
            <div class="col font-weight-bold">Total de Vagas</div>
            <div class="col"><%=@job.quantity%></div>
        </div> 
        <br/>   
        <div class="row">
            <div class="col font-weight-bold">Descrição</div>            
        </div> 
        <br/>         
        <div class="row">
            <div class="col"><%=@job.description%></div>            
        </div>
        <br/>
        <div class="text-center">
          <% if @logado %>
            <td class="col-6"><%= link_to "Editar Vaga", edit_job_path(@job), :class => "btn btn-secondary" %></td>
            <td class="col-6"><%= link_to "Desabilitar Vaga", disable_job_path(@job), method: :post, data:{ confirm: "Essa ação não poderá ser desfeita, confirma?" }, :class => "btn btn-danger" %></td>
            <br/> 
          <% end %> 
          <br/>  
          <% if current_candidate %>
            <p><%= link_to "Quero me cadastrar para essa vaga", make_offer_path(@job), method: :post, data:{ confirm: "Confirma o interesse nessa vaga?" }, :class => "btn btn-success" %></p>            
            <br/> 
          <% end %>
          <p><%=link_to "Voltar", :back, :class => "btn btn-warning" %></p>
        </div>
    </div>
    