config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  devise_for :candidates, path: 'candidates'
  devise_for :employees, path: 'employees', controllers: { registrations: "registrations" }
  resource :search, only: [:show]
  resource :candidate, only: [:show] 
  resources :job_candidates, only: [:index, :show, :edit, :update]
  resources :companies, only: [:index, :edit, :update, :show]
  resources :jobs, only:[:index, :show, :new, :create, :edit, :update] do
    post 'disable', on: :member
  end
  resources :proposals, only: [:new, :create, :edit, :update]  

  namespace 'api', defaults: { format: :json } do
    namespace 'v1' do
      resources :companies, only: [:show]
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
        
    end
end

app/views/home/index.html.erb
<div class="well text-center">
    <div class="col-md-12">Escolha como você deseja acessar o sistema:</div>
    <div class="row">
        <div class="col-md-6">            
            <%= link_to new_employee_session_path, :class => "nav-link" do %>
                <h2>Empresa</h2>
                <%= image_tag("empresa.jpg", alt: "Empresa")%>
            <% end %>
        </div>
        <div class="col-md-6">            
            <%= link_to new_candidate_session_path, :class => "nav-link" do %>
                <h2>Candidato</h2>
                <%= image_tag("candidato.jpg", alt: "Colaborador")%>
            <% end %>
        </div>
    </div>
</div>