config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  devise_for :candidates, path: 'candidates'
  devise_for :employees, path: 'employees', controllers: { registrations: "registrations" }
  resource :search, only: [:show]
  resource :candidate, only: [:show] 
  resources :job_candidates, only: [:index, :show, :edit, :update]
  resources :companies, only: [:index, :edit, :update, :show]
  resources :jobs, only:[:index, :show, :new, :create, :edit, :update] do
    post 'disable', on: :member
  end
  resources :proposals, only: [:new, :create, :edit, :update]  

  namespace 'api', defaults: { format: :json } do
    namespace 'v1' do
      resources :companies, only: [:show]
    end
  end

end

app/models/job_candidate.rb
class JobCandidate < ApplicationRecord
  belongs_to :job
  belongs_to :candidate
  has_one :proposal

  enum status: { pending: 0, declined: 1, proposal: 2, refused:3, accepted: 4  }

  def proposal_status
    self.update_attribute(:status, 2)
  end

  def declined_status
    self.update_attribute(:status, 1)
  end

  def refused_status
    self.update_attribute(:status, 3)
  end  

  def accepted_status
    self.update_attribute(:status, 4)
  end

end

app/controllers/job_candidates_controller.rb
class JobCandidatesController < ApplicationController
    before_action :authenticate_any

    def index
        if current_employee                
            @offers = JobCandidate.all
        else
            if current_candidate
                @offers = JobCandidate.where(candidate: current_candidate)
            else
                @offers = JobCandidate.all
            end
        end
    end

    def show
        @offer = JobCandidate.find(params[:id])
        @job = @offer.job
        @candidate = @offer.candidate  
        @proposal = @offer.proposal      
    end

    def edit
        @offer = JobCandidate.find(params[:id])          
    end

    def update        
        @offer = JobCandidate.find(params[:id]) 
        @offer.update_attribute(:motive, decline_params[:motive])
        @offer.update_attribute(:message, decline_params[:message])
        @offer.declined_status
        redirect_to job_candidates_path
    end

    private
        def decline_params
            params.require(:job_candidate).permit(:motive, :message)            
        end
    
end

app/controllers/jobcandidates_controller.rb
class JobcandidatesController < ApplicationController
    def index
        if current_employee                
            @offers = JobCandidate.all
        else
            if current_candidate
                @offers = JobCandidate.where(candidate: current_candidate)
            else
                @offers = JobCandidate.all
            end
        end
    end

    def show
        @offer = JobCandidate.find(params[:id])
        @job = @offer.job
        @candidate = @offer.candidate
    end
end

app/views/job_candidates/edit.html.erb
<div class="container p-3 my-3 border">
        <h2>Declinando a Candidatura</h2>
        <%=form_with(model:@offer) do |f| %>
                <dt><%= f.label :motive, 'Motivo' %></dt>
                <dd><%= f.text_field :motive %></dd>
                <dt><%= f.label :message, 'Mensagem Personalizada' %></dt>
                <dd><%= f.text_area :message %></dd>          
                <%= f.submit 'Declinar Candidato', class:"btn btn-danger" %>        
        <% end %>
</div>

app/views/job_candidates/index.html.erb
<div class="well text-center">    
  <br/><h2>Relação de Vagas com Ofertas</h2><br/>
</div>
<div class="container">
  <table class="table">
    <thead>
      <tr>
        <th scope="col">Empresa</th>
        <th scope="col">Vaga</th>
        <th scope="col">Candidato</th>
        <th scope="col">Status</th>
        <th scope="col">Link</th>
      </tr>
    </thead>
    <tbody>      
        <% @offers.each do |offer| %>           
          <% if current_employee && offer.job.company == current_employee.company%>    
            <tr>             
              <td><%= offer.job.company.name %>        
              <td><%= offer.job.title %>   
              <td><%= offer.candidate.name %>     
              <td><%= I18n.t("activerecord.attributes.job_candidate.status.#{offer.status}")%></td>
              <td><%= link_to "Ver essa candidatura", job_candidate_path(offer), :class => "btn btn-primary" %>   
            </tr>            
          <% end %>  
          <% if current_candidate && offer.candidate == current_candidate%>    
            <tr>             
              <td><%= offer.job.company.name %>        
              <td><%= offer.job.title %>   
              <td><%= offer.candidate.name %>     
              <td><%= I18n.t("activerecord.attributes.job_candidate.status.#{offer.status}")%></td>
              <td><%= link_to "Ver essa candidatura", job_candidate_path(offer), :class => "btn btn-primary" %>   
            </tr>            
          <% end %>      
        <% end %>        
    </tbody>
  </table>
</div>

app/views/job_candidates/show.html.erb
<!-- Bootstrap -->
<div class="well text-center">    
    <br/><h2>Dados da Empresa</h2><br/>
</div>
<div class="container">
    <h2>Informações da Vaga</h2>
    <br/>
    <div class="row">
        <div class="col-3 font-weight-bold">Empresa</div>
        <div class="col-9"><%= @job.company.name %></div>        
    </div>
    <br/>
    <div class="row">
        <div class="col-3 font-weight-bold">Titulo</div>
        <div class="col-9"><%= @job.title %></div>
    </div>
    <br/>
    <div class="row">
        <div class="col-3 font-weight-bold">Descrição</div>
        <div class="col-9"><%= @job.description %></div>        
    </div>
    <br/>
    <div class="row">
        <div class="col-3 font-weight-bold">Requisitos Obrigatórios</div>
        <div class="col-9"><%= @job.need %></div>        
    </div>
    <br/>
    <div class="row">
        <div class="col-3 font-weight-bold">Faixa Salarial</div>
        <div class="col-3"><%=@job[:salary]%></div>
        <div class="col-3 font-weight-bold">Nível</div>
        <div class="col-3"><%=@job[:stage]%></div>
    </div>
    <br/>
    <div class="row">
        <div class="col-3 font-weight-bold">Data Limite</div>
        <div class="col-3"><%= I18n.localize(@job.expiration, format: :long)%></div>
        <div class="col-3 font-weight-bold">Total de Vagas</div>
        <div class="col-3"><%= @job.quantity %></div>
    </div>
    <br/>
    <h2>Informações do Candidato</h2>
    <br/>
    <div class="row">
        <div class="col-3 font-weight-bold">Nome Completo/Nome Social</div>
        <div class="col-3"><%=@candidate.name%></div>
        <div class="col-3 font-weight-bold">CPF</div>
        <div class="col-3"><%=@candidate.cpf%></div>
    </div>
    <br/>
    <div class="row">
        <div class="col-3 font-weight-bold">E-mail</div>
        <div class="col-3"><%=@candidate.email%></div>
        <div class="col-3 font-weight-bold">Telefone</div>
        <div class="col-3"><%=@candidate.phone%></div>
    </div>
    <br/>
    <div class="row">
        <div class="col-3 font-weight-bold">Biografia Resumida</div>
        <div class="col-9"><%=@candidate.bio%></div>
    </div>
    <br/>
    <h2>Informações da Oferta</h2>
    <br/>
    <div class="row">
        <div class="col-3 font-weight-bold">Status</div>
        <div class="col-9"><span class="alert alert-info"><%= I18n.t("activerecord.attributes.job_candidate.status.#{@offer.status}")%></span></div>
    </div>
    <br/>
    <%if @offer.declined? || @offer.refused?%>
        <div class="row">
            <div class="col-3 font-weight-bold">Motivo</div>
            <div class="col-9"><%=@offer.motive%></div>
        </div>
        <%if @offer.declined?%>
            <div class="row">
                <div class="col-3 font-weight-bold">Mensagem</div>
                <div class="col-9"><%=@offer.message%></div>
            </div>
        <% end %>        
    <%end%>
    <%if @offer.proposal? || @offer.accepted?%>
        <div class="row">
            <div class="col-3 font-weight-bold">Proposta Salarial</div>
            <div class="col-3"><%=@offer.salary_proposal%></div>
            <div class="col-3 font-weight-bold">Data de Inicio</div>
            <div class="col-3"><%= I18n.localize(@offer.start_date, format: :long)%></div>
        </div>
        <br/>
        <div class="row">
                <div class="col-3 font-weight-bold">Mensagem</div>
                <div class="col-9"><%=@offer.message%></div>
        </div>
        <br/>
        <%if @offer.accepted?%>
            <div class="row">
                <div class="col-3 font-weight-bold">Confirmação data de Inicio</div>
                <div class="col-9">
                    <% if @offer.accept_date %>
                        <span class="alert alert-success">ACEITA</span>
                    <% else %>
                        <span class="alert alert-danger">RECUSADA</span>
                    <% end %>
                </div>
            </div>
            <br/>
        <% end %>        
    <%end%>  
    <br/>
    <div class="text-center"> 
     <%if current_employee %>
        <%if @offer.pending?%>
            <td class="col-6"><%= link_to 'Declinar Candidatura', decline_offer_path(@offer), :class => "btn btn-danger" %></td>
            <td class="col-6"><%= link_to 'Enviar Proposta', proposal_offer_path(@offer), :class => "btn btn-success" %></td>
        <%end%>
    <% end %>
    <%if current_candidate %>        
        <%if @offer.proposal?%>
            <p><%= link_to 'Recusar Oferta', refuse_offer_path(@offer), :class => "btn btn-danger" %></p>
                <p><%= link_to 'Aceitar Oferta', accept_offer_path(@offer), :class => "btn btn-success" %></p>
        <%end%>
    <% end %>
    </div>
</div>
<br/>

<p class="well text-center"><%=link_to "Voltar", :back, :class => "btn btn-warning" %></p>